let styling = {
  0: "animation-delay",
  1: "animation-direction",
  2: "animation-duration",
  3: "animation-fill-mode",
  4: "animation-iteration-count",
  5: "animation-name",
  6: "animation-play-state",
  7: "animation-timing-function",
  8: "background-attachment",
  9: "background-blend-mode",
  10: "background-clip",
  11: "background-color",
  12: "background-image",
  13: "background-origin",
  14: "background-position",
  15: "background-repeat",
  16: "background-size",
  17: "border-bottom-color",
  18: "border-bottom-left-radius",
  19: "border-bottom-right-radius",
  20: "border-bottom-style",
  21: "border-bottom-width",
  22: "border-collapse",
  23: "border-image-outset",
  24: "border-image-repeat",
  25: "border-image-slice",
  26: "border-image-source",
  27: "border-image-width",
  28: "border-left-color",
  29: "border-left-style",
  30: "border-left-width",
  31: "border-right-color",
  32: "border-right-style",
  33: "border-right-width",
  34: "border-top-color",
  35: "border-top-left-radius",
  36: "border-top-right-radius",
  37: "border-top-style",
  38: "border-top-width",
  39: "bottom",
  40: "box-shadow",
  41: "box-sizing",
  42: "break-after",
  43: "break-before",
  44: "break-inside",
  45: "caption-side",
  46: "clear",
  47: "clip",
  48: "color",
  49: "content",
  50: "cursor",
  51: "direction",
  52: "display",
  53: "empty-cells",
  54: "float",
  55: "font-family",
  56: "font-kerning",
  57: "font-optical-sizing",
  58: "font-size",
  59: "font-stretch",
  60: "font-style",
  61: "font-variant",
  62: "font-variant-ligatures",
  63: "font-variant-caps",
  64: "font-variant-numeric",
  65: "font-variant-east-asian",
  66: "font-weight",
  67: "height",
  68: "image-orientation",
  69: "image-rendering",
  70: "isolation",
  71: "justify-items",
  72: "justify-self",
  73: "left",
  74: "letter-spacing",
  75: "line-height",
  76: "list-style-image",
  77: "list-style-position",
  78: "list-style-type",
  79: "margin-bottom",
  80: "margin-left",
  81: "margin-right",
  82: "margin-top",
  83: "max-height",
  84: "max-width",
  85: "min-height",
  86: "min-width",
  87: "mix-blend-mode",
  88: "object-fit",
  89: "object-position",
  90: "offset-distance",
  91: "offset-path",
  92: "offset-rotate",
  93: "opacity",
  94: "orphans",
  95: "outline-color",
  96: "outline-offset",
  97: "outline-style",
  98: "outline-width",
  99: "overflow-anchor",
  100: "overflow-wrap",
  101: "overflow-x",
  102: "overflow-y",
  103: "padding-bottom",
  104: "padding-left",
  105: "padding-right",
  106: "padding-top",
  107: "pointer-events",
  108: "position",
  109: "resize",
  110: "right",
  111: "scroll-behavior",
  112: "speak",
  113: "table-layout",
  114: "tab-size",
  115: "text-align",
  116: "text-align-last",
  117: "text-decoration",
  118: "text-decoration-line",
  119: "text-decoration-style",
  120: "text-decoration-color",
  121: "text-decoration-skip-ink",
  122: "text-underline-position",
  123: "text-indent",
  124: "text-rendering",
  125: "text-shadow",
  126: "text-size-adjust",
  127: "text-overflow",
  128: "text-transform",
  129: "top",
  130: "touch-action",
  131: "transition-delay",
  132: "transition-duration",
  133: "transition-property",
  134: "transition-timing-function",
  135: "unicode-bidi",
  136: "vertical-align",
  137: "visibility",
  138: "white-space",
  139: "widows",
  140: "width",
  141: "will-change",
  142: "word-break",
  143: "word-spacing",
  144: "z-index",
  145: "zoom",
  146: "-webkit-appearance",
  147: "backface-visibility",
  148: "-webkit-border-horizontal-spacing",
  149: "-webkit-border-image",
  150: "-webkit-border-vertical-spacing",
  151: "-webkit-box-align",
  152: "-webkit-box-decoration-break",
  153: "-webkit-box-direction",
  154: "-webkit-box-flex",
  155: "-webkit-box-ordinal-group",
  156: "-webkit-box-orient",
  157: "-webkit-box-pack",
  158: "-webkit-box-reflect",
  159: "column-count",
  160: "column-gap",
  161: "column-rule-color",
  162: "column-rule-style",
  163: "column-rule-width",
  164: "column-span",
  165: "column-width",
  166: "backdrop-filter",
  167: "align-content",
  168: "align-items",
  169: "align-self",
  170: "flex-basis",
  171: "flex-grow",
  172: "flex-shrink",
  173: "flex-direction",
  174: "flex-wrap",
  175: "justify-content",
  176: "-webkit-font-smoothing",
  177: "grid-auto-columns",
  178: "grid-auto-flow",
  179: "grid-auto-rows",
  180: "grid-column-end",
  181: "grid-column-start",
  182: "grid-template-areas",
  183: "grid-template-columns",
  184: "grid-template-rows",
  185: "grid-row-end",
  186: "grid-row-start",
  187: "row-gap",
  188: "-webkit-highlight",
  189: "hyphens",
  190: "-webkit-hyphenate-character",
  191: "-webkit-line-break",
  192: "-webkit-line-clamp",
  193: "-webkit-locale",
  194: "-webkit-mask-box-image",
  195: "-webkit-mask-box-image-outset",
  196: "-webkit-mask-box-image-repeat",
  197: "-webkit-mask-box-image-slice",
  198: "-webkit-mask-box-image-source",
  199: "-webkit-mask-box-image-width",
  200: "-webkit-mask-clip",
  201: "-webkit-mask-composite",
  202: "-webkit-mask-image",
  203: "-webkit-mask-origin",
  204: "-webkit-mask-position",
  205: "-webkit-mask-repeat",
  206: "-webkit-mask-size",
  207: "order",
  208: "perspective",
  209: "perspective-origin",
  210: "-webkit-print-color-adjust",
  211: "-webkit-rtl-ordering",
  212: "shape-outside",
  213: "shape-image-threshold",
  214: "shape-margin",
  215: "-webkit-tap-highlight-color",
  216: "-webkit-text-combine",
  217: "-webkit-text-decorations-in-effect",
  218: "-webkit-text-emphasis-color",
  219: "-webkit-text-emphasis-position",
  220: "-webkit-text-emphasis-style",
  221: "-webkit-text-fill-color",
  222: "-webkit-text-orientation",
  223: "-webkit-text-security",
  224: "-webkit-text-stroke-color",
  225: "-webkit-text-stroke-width",
  226: "transform",
  227: "transform-origin",
  228: "transform-style",
  229: "-webkit-user-drag",
  230: "-webkit-user-modify",
  231: "user-select",
  232: "-webkit-writing-mode",
  233: "-webkit-app-region",
  234: "buffered-rendering",
  235: "clip-path",
  236: "clip-rule",
  237: "mask",
  238: "filter",
  239: "flood-color",
  240: "flood-opacity",
  241: "lighting-color",
  242: "stop-color",
  243: "stop-opacity",
  244: "color-interpolation",
  245: "color-interpolation-filters",
  246: "color-rendering",
  247: "fill",
  248: "fill-opacity",
  249: "fill-rule",
  250: "marker-end",
  251: "marker-mid",
  252: "marker-start",
  253: "mask-type",
  254: "shape-rendering",
  255: "stroke",
  256: "stroke-dasharray",
  257: "stroke-dashoffset",
  258: "stroke-linecap",
  259: "stroke-linejoin",
  260: "stroke-miterlimit",
  261: "stroke-opacity",
  262: "stroke-width",
  263: "alignment-baseline",
  264: "baseline-shift",
  265: "dominant-baseline",
  266: "text-anchor",
  267: "writing-mode",
  268: "vector-effect",
  269: "paint-order",
  270: "d",
  271: "cx",
  272: "cy",
  273: "x",
  274: "y",
  275: "r",
  276: "rx",
  277: "ry",
  278: "caret-color",
  279: "line-break",
  alignContent: "normal",
  alignItems: "normal",
  alignSelf: "auto",
  alignmentBaseline: "auto",
  all: "",
  animation: "none 0s ease 0s 1 normal none running",
  animationDelay: "0s",
  animationDirection: "normal",
  animationDuration: "0s",
  animationFillMode: "none",
  animationIterationCount: "1",
  animationName: "none",
  animationPlayState: "running",
  animationTimingFunction: "ease",
  backdropFilter: "none",
  backfaceVisibility: "visible",
  background: "rgb(111, 112, 114) none repeat scroll 0% 0% / auto padding-box border-box",
  backgroundAttachment: "scroll",
  backgroundBlendMode: "normal",
  backgroundClip: "border-box",
  backgroundColor: "rgb(111, 112, 114)",
  backgroundImage: "none",
  backgroundOrigin: "padding-box",
  backgroundPosition: "0% 0%",
  backgroundPositionX: "0%",
  backgroundPositionY: "0%",
  backgroundRepeat: "repeat",
  backgroundRepeatX: "",
  backgroundRepeatY: "",
  backgroundSize: "auto",
  baselineShift: "0px",
  blockSize: "99.9976px",
  border: "0px none rgb(255, 255, 255)",
  borderBlockEnd: "0px none rgb(255, 255, 255)",
  borderBlockEndColor: "rgb(255, 255, 255)",
  borderBlockEndStyle: "none",
  borderBlockEndWidth: "0px",
  borderBlockStart: "0px none rgb(255, 255, 255)",
  borderBlockStartColor: "rgb(255, 255, 255)",
  borderBlockStartStyle: "none",
  borderBlockStartWidth: "0px",
  borderBottom: "0px none rgb(255, 255, 255)",
  borderBottomColor: "rgb(255, 255, 255)",
  borderBottomLeftRadius: "100px",
  borderBottomRightRadius: "100px",
  borderBottomStyle: "none",
  borderBottomWidth: "0px",
  borderCollapse: "separate",
  borderColor: "rgb(255, 255, 255)",
  borderImage: "none",
  borderImageOutset: "0px",
  borderImageRepeat: "stretch",
  borderImageSlice: "100%",
  borderImageSource: "none",
  borderImageWidth: "1",
  borderInlineEnd: "0px none rgb(255, 255, 255)",
  borderInlineEndColor: "rgb(255, 255, 255)",
  borderInlineEndStyle: "none",
  borderInlineEndWidth: "0px",
  borderInlineStart: "0px none rgb(255, 255, 255)",
  borderInlineStartColor: "rgb(255, 255, 255)",
  borderInlineStartStyle: "none",
  borderInlineStartWidth: "0px",
  borderLeft: "0px none rgb(255, 255, 255)",
  borderLeftColor: "rgb(255, 255, 255)",
  borderLeftStyle: "none",
  borderLeftWidth: "0px",
  borderRadius: "100px",
  borderRight: "0px none rgb(255, 255, 255)",
  borderRightColor: "rgb(255, 255, 255)",
  borderRightStyle: "none",
  borderRightWidth: "0px",
  borderSpacing: "0px 0px",
  borderStyle: "none",
  borderTop: "0px none rgb(255, 255, 255)",
  borderTopColor: "rgb(255, 255, 255)",
  borderTopLeftRadius: "100px",
  borderTopRightRadius: "100px",
  borderTopStyle: "none",
  borderTopWidth: "0px",
  borderWidth: "0px",
  bottom: "148.823px",
  boxShadow: "rgba(59, 59, 59, 0.55) 0px 0px 10px 0px",
  boxSizing: "border-box",
  breakAfter: "auto",
  breakBefore: "auto",
  breakInside: "auto",
  bufferedRendering: "auto",
  captionSide: "top",
  caretColor: "rgb(255, 255, 255)",
  clear: "none",
  clip: "auto",
  clipPath: "none",
  clipRule: "nonzero",
  color: "rgb(255, 255, 255)",
  colorInterpolation: "srgb",
  colorInterpolationFilters: "linearrgb",
  colorRendering: "auto",
  colorScheme: "normal",
  columnCount: "auto",
  columnFill: "balance",
  columnGap: "normal",
  columnRule: "0px none rgb(255, 255, 255)",
  columnRuleColor: "rgb(255, 255, 255)",
  columnRuleStyle: "none",
  columnRuleWidth: "0px",
  columnSpan: "none",
  columnWidth: "auto",
  columns: "auto auto",
  contain: "none",
  content: "normal",
  counterIncrement: "none",
  counterReset: "none",
  cssFloat: "none",
  cssText: `animation-delay: 0s, animation-direction: normal, animation-duration: 0s, animation-fill-mode: none, animation-iteration-count: 1, animation-name: none, animation-play-state: running, animation-timing-function: ease, background-attachment: scroll, background-blend-mode: normal, background-clip: border-box, background-color: rgb(111, 112, 114), background-image: none, background-origin: padding-box, background-position: 0% 0%, background-repeat: repeat, background-size: auto, border-bottom-color: rgb(255, 255, 255), border-bottom-left-radius: 100px, border-bottom-right-radius: 100px, border-bottom-style: none, border-bottom-width: 0px, border-collapse: separate, border-image-outset: 0px, border-image-repeat: stretch, border-image-slice: 100%, border-image-source: none, border-image-width: 1, border-left-color: rgb(255, 255, 255), border-left-style: none, border-left-width: 0px, border-right-color: rgb(255, 255, 255), border-right-style: none, border-right-width: 0px, border-top-color: rgb(255, 255, 255), border-top-left-radius: 100px, border-top-right-radius: 100px, border-top-style: none, border-top-width: 0px, bottom: 148.823px, box-shadow: rgba(59, 59, 59, 0.55) 0px 0px 10px 0px, box-sizing: border-box, break-after: auto, break-before: auto, break-inside: auto, caption-side: top, clear: none, clip: auto, color: rgb(255, 255, 255), content: normal, cursor: pointer, direction: ltr, display: block, empty-cells: show, float: none,
    font-family: Segoe UI , font-kerning: auto, font-optical-sizing: auto, font-size: 15px, font-stretch: 100%, font-style: normal, font-variant: normal, font-variant-ligatures: normal, font-variant-caps: normal, font-variant-numeric: normal, font-variant-east-asian: normal, font-weight: 500, height: 99.9976px, image-orientation: from-image, image-rendering: auto, isolation: auto, justify-items: normal, justify-self: auto, left: 207.603px, letter-spacing: normal, line-height: normal, list-style-image: none, list-style-position: outside, list-style-type: disc, margin-bottom: 0px, margin-left: 0px, margin-right: 0px, margin-top: 0px, max-height: none, max-width: none, min-height: 0px, min-width: 0px, mix-blend-mode: normal, object-fit: fill, object-position: 50% 50%, offset-distance: 0px, offset-path: none, offset-rotate: auto 0deg, opacity: 1, orphans: 2, outline-color: rgb(255, 255, 255), outline-offset: 0px, outline-style: none, outline-width: 0px, overflow-anchor: auto, overflow-wrap: normal, overflow-x: visible, overflow-y: visible, padding-bottom: 0px, padding-left: 0px, padding-right: 0px, padding-top: 0px, pointer-events: auto, position: absolute, resize: none, right: 211.407px, scroll-behavior: auto, speak: normal, table-layout: auto, tab-size: 8, text-align: start, text-align-last: auto, text-decoration: none solid rgb(255, 255, 255), text-decoration-line: none, text-decoration-style: solid, text-decoration-color: rgb(255, 255, 255), text-decoration-skip-ink: auto, text-underline-position: auto, text-indent: 0px, text-rendering: auto, text-shadow: none, text-size-adjust: auto, text-overflow: clip, text-transform: none, top: 122.544px, touch-action: auto, transition-delay: 0s, transition-duration: 0s, transition-property: all, transition-timing-function: ease, unicode-bidi: normal, vertical-align: baseline, visibility: visible, white-space: normal, widows: 2, width: 99.9976px, will-change: auto, word-break: normal, word-spacing: 0px, z-index: 1, zoom: 1, -webkit-appearance: none, backface-visibility: visible, -webkit-border-horizontal-spacing: 0px, -webkit-border-image: none, -webkit-border-vertical-spacing: 0px, -webkit-box-align: stretch, -webkit-box-decoration-break: slice, -webkit-box-direction: normal, -webkit-box-flex: 0, -webkit-box-ordinal-group: 1, -webkit-box-orient: horizontal, -webkit-box-pack: start, -webkit-box-reflect: none, column-count: auto, column-gap: normal, column-rule-color: rgb(255, 255, 255), column-rule-style: none, column-rule-width: 0px, column-span: none, column-width: auto, backdrop-filter: none, align-content: normal, align-items: normal, align-self: auto, flex-basis: auto, flex-grow: 0, flex-shrink: 1, flex-direction: row, flex-wrap: nowrap, justify-content: normal, -webkit-font-smoothing: auto, grid-auto-columns: auto, grid-auto-flow: row, grid-auto-rows: auto, grid-column-end: auto, grid-column-start: auto, grid-template-areas: none, grid-template-columns: none, grid-template-rows: none, grid-row-end: auto, grid-row-start: auto, row-gap: normal, -webkit-highlight: none, hyphens: manual, -webkit-hyphenate-character: auto, -webkit-line-break: auto, -webkit-line-clamp: none, -webkit-locale: auto, -webkit-mask-box-image: none, -webkit-mask-box-image-outset: 0px, -webkit-mask-box-image-repeat: stretch, -webkit-mask-box-image-slice: 0 fill, -webkit-mask-box-image-source: none, -webkit-mask-box-image-width: auto, -webkit-mask-clip: border-box, -webkit-mask-composite: source-over, -webkit-mask-image: none, -webkit-mask-origin: border-box, -webkit-mask-position: 0% 0%, -webkit-mask-repeat: repeat, -webkit-mask-size: auto, order: 0, perspective: none, perspective-origin: 49.9928px 49.9928px, -webkit-print-color-adjust: economy, -webkit-rtl-ordering: logical, shape-outside: none, shape-image-threshold: 0, shape-margin: 0px, -webkit-tap-highlight-color: rgba(0, 0, 0, 0.18), -webkit-text-combine: none, -webkit-text-decorations-in-effect: none, -webkit-text-emphasis-color: rgb(255, 255, 255), -webkit-text-emphasis-position: over right, -webkit-text-emphasis-style: none, -webkit-text-fill-color: rgb(255, 255, 255), -webkit-text-orientation: vertical-right, -webkit-text-security: none, -webkit-text-stroke-color: rgb(255, 255, 255), -webkit-text-stroke-width: 0px, transform: none, transform-origin: 49.9988px 49.9988px, transform-style: flat, -webkit-user-drag: auto, -webkit-user-modify: read-only, user-select: auto, -webkit-writing-mode: horizontal-tb, -webkit-app-region: none, buffered-rendering: auto, clip-path: none, clip-rule: nonzero, mask: none, filter: none, flood-color: rgb(0, 0, 0), flood-opacity: 1, lighting-color: rgb(255, 255, 255), stop-color: rgb(0, 0, 0), stop-opacity: 1, color-interpolation: srgb, color-interpolation-filters: linearrgb, color-rendering: auto, fill: rgb(0, 0, 0), fill-opacity: 1, fill-rule: nonzero, marker-end: none, marker-mid: none, marker-start: none, mask-type: luminance, shape-rendering: auto, stroke: none, stroke-dasharray: none, stroke-dashoffset: 0px, stroke-linecap: butt, stroke-linejoin: miter, stroke-miterlimit: 4, stroke-opacity: 1, stroke-width: 1px, alignment-baseline: auto, baseline-shift: 0px, dominant-baseline: auto, text-anchor: start, writing-mode: horizontal-tb, vector-effect: none, paint-order: normal, d: none, cx: 0px, cy: 0px, x: 0px, y: 0px, r: 0px, rx: auto, ry: auto, caret-color: rgb(255, 255, 255), line-break: auto `,
  cursor: "pointer",
  cx: "0px",
  cy: "0px",
  d: "none",
  direction: "ltr",
  display: "block",
  dominantBaseline: "auto",
  emptyCells: "show",
  fill: "rgb(0, 0, 0)",
  fillOpacity: "1",
  fillRule: "nonzero",
  filter: "none",
  flex: "0 1 auto",
  flexBasis: "auto",
  flexDirection: "row",
  flexFlow: "row nowrap",
  flexGrow: "0",
  flexShrink: "1",
  flexWrap: "nowrap",
  float: "none",
  floodColor: "rgb(0, 0, 0)",
  floodOpacity: "1",
  font: "500 15px 'Segoe UI'",
  fontDisplay: "",
  fontFamily: "'Segoe UI '",
  fontFeatureSettings: "normal",
  fontKerning: "auto",
  fontOpticalSizing: "auto",
  fontSize: "15px",
  fontStretch: "100%",
  fontStyle: "normal",
  fontVariant: "normal",
  fontVariantCaps: "normal",
  fontVariantEastAsian: "normal",
  fontVariantLigatures: "normal",
  fontVariantNumeric: "normal",
  fontVariationSettings: "normal",
  fontWeight: "500",
  gap: "normal",
  grid: "none / none / none / row / auto / auto",
  gridArea: "auto / auto / auto / auto",
  gridAutoColumns: "auto",
  gridAutoFlow: "row",
  gridAutoRows: "auto",
  gridColumn: "auto / auto",
  gridColumnEnd: "auto",
  gridColumnGap: "normal",
  gridColumnStart: "auto",
  gridGap: "normal normal",
  gridRow: "auto / auto",
  gridRowEnd: "auto",
  gridRowGap: "normal",
  gridRowStart: "auto",
  gridTemplate: "none / none / none",
  gridTemplateAreas: "none",
  gridTemplateColumns: "none",
  gridTemplateRows: "none",
  height: "99.9976px",
  hyphens: "manual",
  imageOrientation: "from-image",
  imageRendering: "auto",
  inlineSize: "99.9976px",
  isolation: "auto",
  justifyContent: "normal",
  justifyItems: "normal",
  justifySelf: "auto",
  left: "207.603px",
  length: 280,
  letterSpacing: "normal",
  lightingColor: "rgb(255, 255, 255)",
  lineBreak: "auto",
  lineHeight: "normal",
  listStyle: "outside none disc",
  listStyleImage: "none",
  listStylePosition: "outside",
  listStyleType: "disc",
  margin: "0px",
  marginBlockEnd: "0px",
  marginBlockStart: "0px",
  marginBottom: "0px",
  marginInlineEnd: "0px",
  marginInlineStart: "0px",
  marginLeft: "0px",
  marginRight: "0px",
  marginTop: "0px",
  marker: "none",
  markerEnd: "none",
  markerMid: "none",
  markerStart: "none",
  mask: "none",
  maskType: "luminance",
  maxBlockSize: "none",
  maxHeight: "none",
  maxInlineSize: "none",
  maxWidth: "none",
  maxZoom: "",
  minBlockSize: "0px",
  minHeight: "0px",
  minInlineSize: "0px",
  minWidth: "0px",
  minZoom: "",
  mixBlendMode: "normal",
  objectFit: "fill",
  objectPosition: "50% 50%",
  offset: "none 0px auto 0deg",
  offsetDistance: "0px",
  offsetPath: "none",
  offsetRotate: "auto 0deg",
  opacity: "1",
  order: "0",
  orientation: "",
  orphans: "2",
  outline: "rgb(255, 255, 255) none 0px",
  outlineColor: "rgb(255, 255, 255)",
  outlineOffset: "0px",
  outlineStyle: "none",
  outlineWidth: "0px",
  overflow: "visible",
  overflowAnchor: "auto",
  overflowWrap: "normal",
  overflowX: "visible",
  overflowY: "visible",
  overscrollBehavior: "auto",
  overscrollBehaviorBlock: "auto",
  overscrollBehaviorInline: "auto",
  overscrollBehaviorX: "auto",
  overscrollBehaviorY: "auto",
  padding: "0px",
  paddingBlockEnd: "0px",
  paddingBlockStart: "0px",
  paddingBottom: "0px",
  paddingInlineEnd: "0px",
  paddingInlineStart: "0px",
  paddingLeft: "0px",
  paddingRight: "0px",
  paddingTop: "0px",
  page: "",
  pageBreakAfter: "auto",
  pageBreakBefore: "auto",
  pageBreakInside: "auto",
  paintOrder: "normal",
  parentRule: null,
  perspective: "none",
  perspectiveOrigin: "49.9928px 49.9928px",
  placeContent: "normal",
  placeItems: "normal",
  placeSelf: "auto",
  pointerEvents: "auto",
  position: "absolute",
  quotes: "",
  r: "0px",
  resize: "none",
  right: "211.407px",
  rowGap: "normal",
  rx: "auto",
  ry: "auto",
  scrollBehavior: "auto",
  scrollMargin: "0px",
  scrollMarginBlock: "0px",
  scrollMarginBlockEnd: "0px",
  scrollMarginBlockStart: "0px",
  scrollMarginBottom: "0px",
  scrollMarginInline: "0px",
  scrollMarginInlineEnd: "0px",
  scrollMarginInlineStart: "0px",
  scrollMarginLeft: "0px",
  scrollMarginRight: "0px",
  scrollMarginTop: "0px",
  scrollPadding: "auto",
  scrollPaddingBlock: "auto",
  scrollPaddingBlockEnd: "auto",
  scrollPaddingBlockStart: "auto",
  scrollPaddingBottom: "auto",
  scrollPaddingInline: "auto",
  scrollPaddingInlineEnd: "auto",
  scrollPaddingInlineStart: "auto",
  scrollPaddingLeft: "auto",
  scrollPaddingRight: "auto",
  scrollPaddingTop: "auto",
  scrollSnapAlign: "none",
  scrollSnapStop: "normal",
  scrollSnapType: "none",
  shapeImageThreshold: "0",
  shapeMargin: "0px",
  shapeOutside: "none",
  shapeRendering: "auto",
  size: "",
  speak: "normal",
  src: "",
  stopColor: "rgb(0, 0, 0)",
  stopOpacity: "1",
  stroke: "none",
  strokeDasharray: "none",
  strokeDashoffset: "0px",
  strokeLinecap: "butt",
  strokeLinejoin: "miter",
  strokeMiterlimit: "4",
  strokeOpacity: "1",
  strokeWidth: "1px",
  tabSize: "8",
  tableLayout: "auto",
  textAlign: "start",
  textAlignLast: "auto",
  textAnchor: "start",
  textCombineUpright: "none",
  textDecoration: "none solid rgb(255, 255, 255)",
  textDecorationColor: "rgb(255, 255, 255)",
  textDecorationLine: "none",
  textDecorationSkipInk: "auto",
  textDecorationStyle: "solid",
  textIndent: "0px",
  textOrientation: "mixed",
  textOverflow: "clip",
  textRendering: "auto",
  textShadow: "none",
  textSizeAdjust: "auto",
  textTransform: "none",
  textUnderlinePosition: "auto",
  top: "122.544px",
  touchAction: "auto",
  transform: "none",
  transformBox: "view-box",
  transformOrigin: "49.9988px 49.9988px",
  transformStyle: "flat",
  transition: "all 0s ease 0s",
  transitionDelay: "0s",
  transitionDuration: "0s",
  transitionProperty: "all",
  transitionTimingFunction: "ease",
  unicodeBidi: "normal",
  unicodeRange: "",
  userSelect: "auto",
  userZoom: "",
  vectorEffect: "none",
  verticalAlign: "baseline",
  visibility: "visible",
  webkitAlignContent: "normal",
  webkitAlignItems: "normal",
  webkitAlignSelf: "auto",
  webkitAnimation: "none 0s ease 0s 1 normal none running",
  webkitAnimationDelay: "0s",
  webkitAnimationDirection: "normal",
  webkitAnimationDuration: "0s",
  webkitAnimationFillMode: "none",
  webkitAnimationIterationCount: "1",
  webkitAnimationName: "none",
  webkitAnimationPlayState: "running",
  webkitAnimationTimingFunction: "ease",
  webkitAppRegion: "none",
  webkitAppearance: "none",
  webkitBackfaceVisibility: "visible",
  webkitBackgroundClip: "border-box",
  webkitBackgroundOrigin: "padding-box",
  webkitBackgroundSize: "auto",
  webkitBorderAfter: "0px none rgb(255, 255, 255)",
  webkitBorderAfterColor: "rgb(255, 255, 255)",
  webkitBorderAfterStyle: "none",
  webkitBorderAfterWidth: "0px",
  webkitBorderBefore: "0px none rgb(255, 255, 255)",
  webkitBorderBeforeColor: "rgb(255, 255, 255)",
  webkitBorderBeforeStyle: "none",
  webkitBorderBeforeWidth: "0px",
  webkitBorderBottomLeftRadius: "100px",
  webkitBorderBottomRightRadius: "100px",
  webkitBorderEnd: "0px none rgb(255, 255, 255)",
  webkitBorderEndColor: "rgb(255, 255, 255)",
  webkitBorderEndStyle: "none",
  webkitBorderEndWidth: "0px",
  webkitBorderHorizontalSpacing: "0px",
  webkitBorderImage: "none",
  webkitBorderRadius: "100px",
  webkitBorderStart: "0px none rgb(255, 255, 255)",
  webkitBorderStartColor: "rgb(255, 255, 255)",
  webkitBorderStartStyle: "none",
  webkitBorderStartWidth: "0px",
  webkitBorderTopLeftRadius: "100px",
  webkitBorderTopRightRadius: "100px",
  webkitBorderVerticalSpacing: "0px",
  webkitBoxAlign: "stretch",
  webkitBoxDecorationBreak: "slice",
  webkitBoxDirection: "normal",
  webkitBoxFlex: "0",
  webkitBoxOrdinalGroup: "1",
  webkitBoxOrient: "horizontal",
  webkitBoxPack: "start",
  webkitBoxReflect: "none",
  webkitBoxShadow: "rgba(59, 59, 59, 0.55) 0px 0px 10px 0px",
  webkitBoxSizing: "border-box",
  webkitClipPath: "none",
  webkitColumnBreakAfter: "auto",
  webkitColumnBreakBefore: "auto",
  webkitColumnBreakInside: "auto",
  webkitColumnCount: "auto",
  webkitColumnGap: "normal",
  webkitColumnRule: "0px none rgb(255, 255, 255)",
  webkitColumnRuleColor: "rgb(255, 255, 255)",
  webkitColumnRuleStyle: "none",
  webkitColumnRuleWidth: "0px",
  webkitColumnSpan: "none",
  webkitColumnWidth: "auto",
  webkitColumns: "auto auto",
  webkitFilter: "none",
  webkitFlex: "0 1 auto",
  webkitFlexBasis: "auto",
  webkitFlexDirection: "row",
  webkitFlexFlow: "row nowrap",
  webkitFlexGrow: "0",
  webkitFlexShrink: "1",
  webkitFlexWrap: "nowrap",
  webkitFontFeatureSettings: "normal",
  webkitFontSizeDelta: "",
  webkitFontSmoothing: "auto",
  webkitHighlight: "none",
  webkitHyphenateCharacter: "auto",
  webkitJustifyContent: "normal",
  webkitLineBreak: "auto",
  webkitLineClamp: "none",
  webkitLocale: "auto",
  webkitLogicalHeight: "99.9976px",
  webkitLogicalWidth: "99.9976px",
  webkitMarginAfter: "0px",
  webkitMarginBefore: "0px",
  webkitMarginEnd: "0px",
  webkitMarginStart: "0px",
  webkitMask: "",
  webkitMaskBoxImage: "none",
  webkitMaskBoxImageOutset: "0px",
  webkitMaskBoxImageRepeat: "stretch",
  webkitMaskBoxImageSlice: "0 fill",
  webkitMaskBoxImageSource: "none",
  webkitMaskBoxImageWidth: "auto",
  webkitMaskClip: "border-box",
  webkitMaskComposite: "source-over",
  webkitMaskImage: "none",
  webkitMaskOrigin: "border-box",
  webkitMaskPosition: "0% 0%",
  webkitMaskPositionX: "0%",
  webkitMaskPositionY: "0%",
  webkitMaskRepeat: "repeat",
  webkitMaskRepeatX: "",
  webkitMaskRepeatY: "",
  webkitMaskSize: "auto",
  webkitMaxLogicalHeight: "none",
  webkitMaxLogicalWidth: "none",
  webkitMinLogicalHeight: "0px",
  webkitMinLogicalWidth: "0px",
  webkitOpacity: "1",
  webkitOrder: "0",
  webkitPaddingAfter: "0px",
  webkitPaddingBefore: "0px",
  webkitPaddingEnd: "0px",
  webkitPaddingStart: "0px",
  webkitPerspective: "none",
  webkitPerspectiveOrigin: "49.9928px 49.9928px",
  webkitPerspectiveOriginX: "",
  webkitPerspectiveOriginY: "",
  webkitPrintColorAdjust: "economy",
  webkitRtlOrdering: "logical",
  webkitRubyPosition: "before",
  webkitShapeImageThreshold: "0",
  webkitShapeMargin: "0px",
  webkitShapeOutside: "none",
  webkitTapHighlightColor: "rgba(0, 0, 0, 0.18)",
  webkitTextCombine: "none",
  webkitTextDecorationsInEffect: "none",
  webkitTextEmphasis: "",
  webkitTextEmphasisColor: "rgb(255, 255, 255)",
  webkitTextEmphasisPosition: "over right",
  webkitTextEmphasisStyle: "none",
  webkitTextFillColor: "rgb(255, 255, 255)",
  webkitTextOrientation: "vertical-right",
  webkitTextSecurity: "none",
  webkitTextSizeAdjust: "auto",
  webkitTextStroke: "",
  webkitTextStrokeColor: "rgb(255, 255, 255)",
  webkitTextStrokeWidth: "0px",
  webkitTransform: "none",
  webkitTransformOrigin: "49.9988px 49.9988px",
  webkitTransformOriginX: "",
  webkitTransformOriginY: "",
  webkitTransformOriginZ: "",
  webkitTransformStyle: "flat",
  webkitTransition: "all 0s ease 0s",
  webkitTransitionDelay: "0s",
  webkitTransitionDuration: "0s",
  webkitTransitionProperty: "all",
  webkitTransitionTimingFunction: "ease",
  webkitUserDrag: "auto",
  webkitUserModify: "read-only",
  webkitUserSelect: "auto",
  webkitWritingMode: "horizontal-tb",
  whiteSpace: "normal",
  widows: "2",
  width: "99.9976px",
  willChange: "auto",
  wordBreak: "normal",
  wordSpacing: "0px",
  wordWrap: "normal",
  writingMode: "horizontal-tb",
  x: "0px",
  y: "0px",
  zIndex: "1",
  zoom: "1"
}